"""
Music Duplicate Undo  v2.5
===========================
Reads a CSV report generated by find_music_duplicates.py and moves files
back to their original locations in the unsorted folder.

Usage:
    python undo_duplicates.py "C:\\Music\\Duplicates\\music_report_TIMESTAMP.csv"

Options:
    --dry-run                     Preview what would be restored, nothing moves
    --list                        Show a summary of what the CSV contains and exit
    --list-categories             Show all categories found in the CSV and exit
    --filter-category CATEGORY    Only undo a specific category
    --filter-method METHOD        Only undo files matched by a specific method
                                  e.g. --filter-method "audio fingerprint"
                                       --filter-method "filename/metadata"
"""

import sys
import csv
import shutil
from pathlib import Path
from datetime import datetime
from collections import Counter

sys.path.insert(0, str(Path(__file__).parent.parent))
from music_tools_common import load_csv
from music_tools_common import interactive_options


# -- Helpers -------------------------------------------------------------------
def was_moved(action: str) -> bool:
    a = action.strip().lower()
    return a.startswith("auto-moved") or a.startswith("moved to")


def get_moved_rows(rows: list[dict]) -> list[dict]:
    """Return rows where a file was actually moved (not dry-run rows)."""
    result = []
    for row in rows:
        action = row.get("Action", "").strip()
        if not was_moved(action):
            continue
        if "would" in action.lower():
            continue
        result.append(row)
    return result


def apply_filters(rows: list[dict],
                  filter_category: str | None = None,
                  filter_method: str | None = None) -> list[dict]:
    result = rows
    if filter_category:
        result = [r for r in result
                  if r.get("Category", "").strip().lower() == filter_category.lower()]
    if filter_method:
        result = [r for r in result
                  if filter_method.lower() in r.get("Match Method", "").strip().lower()]
    return result


def fmt_size(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024:
            return f"{n:.1f} {unit}"
        n /= 1024
    return f"{n:.1f} TB"


# -- List / summary ------------------------------------------------------------
def cmd_list(csv_path: Path, log_callback=None) -> dict:
    """Print a full summary of what the CSV contains."""
    _log = log_callback or print

    all_rows = load_csv(csv_path)
    moved    = get_moved_rows(all_rows)

    _log("=" * 65)
    _log("Music Duplicate Report \u2014 Summary")
    _log("=" * 65)
    _log(f"  File              : {csv_path.name}")
    _log(f"  Total rows        : {len(all_rows)}")
    _log(f"  Files moved       : {len(moved)}")
    _log(f"  Other rows        : {len(all_rows) - len(moved)}")
    _log("")

    cat_counts = Counter(r.get("Category", "\u2014") for r in moved)
    _log("  By category:")
    for cat, count in cat_counts.most_common():
        _log(f"    {count:>5}  {cat}")
    _log("")

    method_counts = Counter(r.get("Match Method", "\u2014") for r in moved)
    _log("  By match method:")
    for method, count in method_counts.most_common():
        _log(f"    {count:>5}  {method or chr(8212)}")
    _log("")

    _log(f"  Files that can be restored ({len(moved)}):")
    _log("")
    for r in moved:
        cat      = r.get("Category", "").strip()
        orig     = r.get("Unsorted Path", "").strip()
        dest     = r.get("Destination Path", "").strip()
        method   = r.get("Match Method", "").strip()

        orig_exists = Path(orig).exists() if orig else False
        dest_exists = Path(dest).exists() if dest else False

        status = ""
        if not dest_exists:
            status = "  [!] Not at destination \u2014 may already be restored or deleted"
        elif orig_exists:
            status = "  [!] File already exists at original location"

        _log(f"  [{cat}] {Path(orig).name if orig else chr(8212)}")
        if method:   _log(f"    Method  : {method}")
        if dest:     _log(f"    Current : {dest}  {chr(10003) if dest_exists else chr(10007) + ' missing'}")
        if orig:     _log(f"    Original: {orig}  {chr(10003) + ' exists' if orig_exists else ''}")
        if status:   _log(f"   {status}")
        _log("")

    _log("=" * 65)
    return {"rows": all_rows, "moved": moved, "report_path": None}


def cmd_list_categories(csv_path: Path, log_callback=None) -> dict:
    """Print all categories and match methods found in the CSV."""
    _log = log_callback or print

    all_rows = load_csv(csv_path)
    moved    = get_moved_rows(all_rows)

    _log(f"\nCSV: {csv_path.name}")
    _log(f"Total moved rows: {len(moved)}\n")

    cats = Counter(r.get("Category", "\u2014") for r in moved)
    _log("Categories:")
    for cat, count in cats.most_common():
        _log(f"  {count:>4}  {cat}")

    methods = Counter(r.get("Match Method", "\u2014") for r in moved)
    _log("\nMatch methods:")
    for m, count in methods.most_common():
        _log(f"  {count:>4}  {m or chr(8212)}")
    _log("")

    return {"rows": all_rows, "moved": moved, "report_path": None}


# -- Undo ----------------------------------------------------------------------
def cmd_undo(csv_path: Path, dry_run: bool = True,
             filter_category: str | None = None,
             filter_method: str | None = None,
             progress_callback=None, log_callback=None) -> dict:
    _log = log_callback or print

    _log("=" * 65)
    _log("Music Duplicate Undo")
    if dry_run:
        _log("*** DRY RUN: No files will be moved ***")
    _log(f"Started  : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    _log(f"CSV file : {csv_path}")
    if filter_category:
        _log(f"Filter   : category = {filter_category}")
    if filter_method:
        _log(f"Filter   : method   = {filter_method}")
    _log("=" * 65)

    all_rows = load_csv(csv_path)
    moved    = get_moved_rows(all_rows)
    rows     = apply_filters(moved, filter_category=filter_category,
                             filter_method=filter_method)

    if not moved:
        _log("\nNo moved files found in this CSV.")
        _log("(Only rows with \'Moved to\' or \'Auto-moved\' actions can be restored.)")
        return {"restored": 0, "skipped": 0, "errors": 0, "report_path": None}

    if not rows:
        _log(f"\nNo rows matched the current filters ({len(moved)} moved rows in CSV).")
        return {"restored": 0, "skipped": 0, "errors": 0, "report_path": None}

    _log(f"\nFound {len(rows)} file(s) to restore.\n")

    restored = 0
    skipped  = 0
    errors   = 0
    total    = len(rows)

    for i, row in enumerate(rows, 1):
        category     = row.get("Category", "").strip()
        method       = row.get("Match Method", "").strip()
        original_str = row.get("Unsorted Path", "").strip()
        current_str  = row.get("Destination Path", "").strip()

        if progress_callback:
            progress_callback(i, total, Path(current_str).name if current_str else "")

        if not original_str or not current_str:
            _log("[SKIP]  Missing path data \u2014 skipping.")
            skipped += 1
            continue

        original = Path(original_str)
        current  = Path(current_str)

        label = f"[{category}]" + (f" [{method}]" if method else "")
        _log(label)

        if not current.exists():
            _log(f"  [MISSING]  File not at destination \u2014 may already be restored:")
            _log(f"             {current}")
            skipped += 1
            _log("")
            continue

        if original.exists():
            _log(f"  [SKIP]  File already exists at original location:")
            _log(f"          {original}")
            skipped += 1
            _log("")
            continue

        if dry_run:
            _log(f"  [WOULD RESTORE] {current}")
            _log(f"              \u2192  {original}")
            restored += 1
        else:
            try:
                original.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(current), str(original))
                _log(f"  [RESTORED] {current}")
                _log(f"          \u2192  {original}")
                restored += 1
            except Exception as e:
                _log(f"  [ERROR]  {current}")
                _log(f"           Reason: {e}")
                errors += 1
        _log("")

    _log("=" * 65)
    _log("SUMMARY")
    if dry_run:
        _log(f"  Would restore  : {restored}")
    else:
        _log(f"  Restored       : {restored}")
    _log(f"  Skipped        : {skipped}")
    _log(f"  Errors         : {errors}")
    _log("=" * 65)

    return {"restored": restored, "skipped": skipped, "errors": errors,
            "report_path": None}


# -- GUI-callable core ---------------------------------------------------------
def run_undo_duplicates(
    csv_path,
    mode="undo",              # "undo" | "list" | "list-categories"
    dry_run=True,
    filter_category=None,
    filter_method=None,
    progress_callback=None,
    log_callback=None,
) -> dict:
    """
    GUI-callable entry point for the music duplicate undo tool.

    Parameters
    ----------
    csv_path : str | Path
        Path to the CSV report generated by find_music_duplicates.py.
    mode : str
        "undo"             -- restore moved files to their original locations.
        "list"             -- summarise the CSV; no files are moved.
        "list-categories"  -- show category / method breakdown; no files moved.
    dry_run : bool
        If True, preview actions without moving anything (default: True).
    filter_category : str | None
        Only undo files in this category (case-insensitive).
    filter_method : str | None
        Only undo files matched by this method (substring match).
    progress_callback : callable | None
        Called as progress_callback(current, total, filename).
    log_callback : callable | None
        Called as log_callback(message) for each output line.

    Returns
    -------
    dict with keys: report_path (always None — no CSV generated), plus
    mode-specific keys (restored/skipped/errors for undo; rows/moved for list).

    Raises
    ------
    ValueError
        If csv_path does not exist or mode is invalid.
    """
    csv_path = Path(csv_path)
    if not csv_path.exists():
        raise ValueError(f"CSV report not found: {csv_path}")

    if mode == "list":
        return cmd_list(csv_path, log_callback=log_callback)
    elif mode == "list-categories":
        return cmd_list_categories(csv_path, log_callback=log_callback)
    elif mode == "undo":
        return cmd_undo(csv_path, dry_run=dry_run,
                        filter_category=filter_category,
                        filter_method=filter_method,
                        progress_callback=progress_callback,
                        log_callback=log_callback)
    else:
        raise ValueError(
            f"Unknown mode: {mode!r}. Expected \'undo\', \'list\', or \'list-categories\'."
        )


# -- CLI entry point -----------------------------------------------------------
def main():
    interactive_options([
        ("--dry-run", "Dry run \u2014 preview only, no files changed  (default is live mode)"),
    ])

    DRY_RUN         = "--dry-run"         in sys.argv
    LIST_SUMMARY    = "--list"            in sys.argv
    LIST_CATEGORIES = "--list-categories" in sys.argv

    _filter_cat = next(
        (sys.argv[i + 1] for i, a in enumerate(sys.argv)
         if a == "--filter-category" and i + 1 < len(sys.argv)), None,
    )
    _filter_method = next(
        (sys.argv[i + 1] for i, a in enumerate(sys.argv)
         if a == "--filter-method" and i + 1 < len(sys.argv)), None,
    )

    pos_args = [a for a in sys.argv[1:]
                if not a.startswith("--") and a not in (
                    _filter_cat or "", _filter_method or "")]

    if not pos_args:
        print("Usage: python undo_duplicates.py <path_to_csv_report> [options]")
        print()
        print("Options:")
        print("  --dry-run                      Preview only, nothing moves")
        print("  --list                         Full summary of the CSV contents")
        print("  --list-categories              Show categories and match methods")
        print("  --filter-category CATEGORY     Only undo a specific category")
        print("  --filter-method METHOD         Only undo a specific match method")
        print()
        print("Examples:")
        print(r'  python undo_duplicates.py "C:\Music\report.csv"')
        print(r'  python undo_duplicates.py "C:\Music\report.csv" --dry-run')
        print(r'  python undo_duplicates.py "C:\Music\report.csv" --list')
        print(r'  python undo_duplicates.py "C:\Music\report.csv" --list-categories')
        print(r'  python undo_duplicates.py "C:\Music\report.csv" --filter-category "Exact Match"')
        print(r'  python undo_duplicates.py "C:\Music\report.csv" --filter-method "audio fingerprint"')
        sys.exit(1)

    csv_file = Path(pos_args[0].strip('"'))
    mode = "list" if LIST_SUMMARY else "list-categories" if LIST_CATEGORIES else "undo"

    try:
        run_undo_duplicates(
            csv_path=csv_file,
            mode=mode,
            dry_run=DRY_RUN,
            filter_category=_filter_cat,
            filter_method=_filter_method,
        )
    except ValueError as exc:
        print(f"ERROR: {exc}")
        sys.exit(1)


if __name__ == "__main__":
    main()
