"""
Music Duplicate Undo  v2.2
===========================
Reads a CSV report generated by find_music_duplicates.py and moves files
back to their original locations in the unsorted folder.

Usage:
    python undo_duplicates.py "C:\\Music\\Duplicates\\music_report_TIMESTAMP.csv"

Options:
    --dry-run                     Preview what would be restored, nothing moves
    --list                        Show a summary of what the CSV contains and exit
    --list-categories             Show all categories found in the CSV and exit
    --filter-category CATEGORY    Only undo a specific category
    --filter-method METHOD        Only undo files matched by a specific method
                                  e.g. --filter-method "audio fingerprint"
                                       --filter-method "filename/metadata"
"""

import sys
import csv
import shutil
from pathlib import Path
from datetime import datetime
from collections import Counter

# ── Parse flags ────────────────────────────────────────────────────────────────
DRY_RUN          = "--dry-run"         in sys.argv
LIST_SUMMARY     = "--list"            in sys.argv
LIST_CATEGORIES  = "--list-categories" in sys.argv

_filter_cat = next(
    (sys.argv[i + 1] for i, a in enumerate(sys.argv)
     if a == "--filter-category" and i + 1 < len(sys.argv)), None,
)
_filter_method = next(
    (sys.argv[i + 1] for i, a in enumerate(sys.argv)
     if a == "--filter-method" and i + 1 < len(sys.argv)), None,
)
FILTER_CATEGORY = _filter_cat
FILTER_METHOD   = _filter_method


# ── Helpers ────────────────────────────────────────────────────────────────────
def was_moved(action: str) -> bool:
    a = action.strip().lower()
    return a.startswith("auto-moved") or a.startswith("moved to")


def load_csv(csv_path: Path) -> list[dict]:
    rows = []
    with open(csv_path, encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            rows.append(row)
    return rows


def get_moved_rows(rows: list[dict]) -> list[dict]:
    """Return rows where a file was actually moved (not dry-run rows)."""
    result = []
    for row in rows:
        action = row.get("Action", "").strip()
        if not was_moved(action):
            continue
        if "would" in action.lower():
            continue
        result.append(row)
    return result


def apply_filters(rows: list[dict]) -> list[dict]:
    result = rows
    if FILTER_CATEGORY:
        result = [r for r in result
                  if r.get("Category", "").strip().lower() == FILTER_CATEGORY.lower()]
    if FILTER_METHOD:
        result = [r for r in result
                  if FILTER_METHOD.lower() in r.get("Match Method", "").strip().lower()]
    return result


def fmt_size(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024:
            return f"{n:.1f} {unit}"
        n /= 1024
    return f"{n:.1f} TB"


# ── List / summary ─────────────────────────────────────────────────────────────
def cmd_list(csv_path: Path):
    """Print a full summary of what the CSV contains."""
    if not csv_path.exists():
        print(f"ERROR: File not found: {csv_path}")
        sys.exit(1)

    all_rows  = load_csv(csv_path)
    moved     = get_moved_rows(all_rows)

    print("=" * 65)
    print("Music Duplicate Report — Summary")
    print("=" * 65)
    print(f"  File     : {csv_path.name}")
    print(f"  Total rows        : {len(all_rows)}")
    print(f"  Files moved       : {len(moved)}")
    print(f"  Other rows        : {len(all_rows) - len(moved)}")
    print()

    # Category breakdown
    cat_counts = Counter(r.get("Category", "—") for r in moved)
    print("  By category:")
    for cat, count in cat_counts.most_common():
        print(f"    {count:>5}  {cat}")
    print()

    # Method breakdown
    method_counts = Counter(r.get("Match Method", "—") for r in moved)
    print("  By match method:")
    for method, count in method_counts.most_common():
        print(f"    {count:>5}  {method or '—'}")
    print()

    # File listing
    print(f"  Files that can be restored ({len(moved)}):")
    print()
    for r in moved:
        cat      = r.get("Category", "").strip()
        orig     = r.get("Unsorted Path", "").strip()
        dest     = r.get("Destination Path", "").strip()
        method   = r.get("Match Method", "").strip()
        size_str = r.get("Unsorted Size", "").strip()

        orig_exists = Path(orig).exists() if orig else False
        dest_exists = Path(dest).exists() if dest else False

        status = ""
        if not dest_exists:  status = "  [!] Not at destination — may already be restored or deleted"
        elif orig_exists:    status = "  [!] File already exists at original location"

        print(f"  [{cat}] {Path(orig).name if orig else '—'}")
        if method:  print(f"    Method  : {method}")
        if dest:    print(f"    Current : {dest}  {'✓' if dest_exists else '✗ missing'}")
        if orig:    print(f"    Original: {orig}  {'✓ exists' if orig_exists else ''}")
        if status:  print(f"   {status}")
        print()

    print("=" * 65)


def cmd_list_categories(csv_path: Path):
    """Print all categories and match methods found in the CSV."""
    if not csv_path.exists():
        print(f"ERROR: File not found: {csv_path}")
        sys.exit(1)

    all_rows = load_csv(csv_path)
    moved    = get_moved_rows(all_rows)

    print(f"\nCSV: {csv_path.name}")
    print(f"Total moved rows: {len(moved)}\n")

    cats = Counter(r.get("Category","—") for r in moved)
    print("Categories:")
    for cat, count in cats.most_common():
        print(f"  {count:>4}  {cat}")

    methods = Counter(r.get("Match Method","—") for r in moved)
    print("\nMatch methods:")
    for m, count in methods.most_common():
        print(f"  {count:>4}  {m or '—'}")
    print()


# ── Undo ───────────────────────────────────────────────────────────────────────
def undo(csv_path: Path):
    if not csv_path.exists():
        print(f"ERROR: CSV file not found: {csv_path}")
        sys.exit(1)

    print("=" * 65)
    print("Music Duplicate Undo")
    if DRY_RUN:
        print("*** DRY RUN: No files will be moved ***")
    print(f"Started  : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"CSV file : {csv_path}")
    if FILTER_CATEGORY:
        print(f"Filter   : category = {FILTER_CATEGORY}")
    if FILTER_METHOD:
        print(f"Filter   : method   = {FILTER_METHOD}")
    print("=" * 65)

    all_rows = load_csv(csv_path)
    moved    = get_moved_rows(all_rows)
    rows     = apply_filters(moved)

    if not moved:
        print("\nNo moved files found in this CSV.")
        print("(Only rows with 'Moved to' or 'Auto-moved' actions can be restored.)")
        return

    if not rows:
        print(f"\nNo rows matched the current filters ({len(moved)} moved rows in CSV).")
        return

    print(f"\nFound {len(rows)} file(s) to restore.\n")

    restored = 0
    skipped  = 0
    errors   = 0

    for row in rows:
        category     = row.get("Category", "").strip()
        method       = row.get("Match Method", "").strip()
        original_str = row.get("Unsorted Path", "").strip()
        current_str  = row.get("Destination Path", "").strip()

        if not original_str or not current_str:
            print(f"[SKIP]  Missing path data — skipping.")
            skipped += 1
            continue

        original = Path(original_str)
        current  = Path(current_str)

        label = f"[{category}]" + (f" [{method}]" if method else "")
        print(label)

        if not current.exists():
            print(f"  [MISSING]  File not at destination — may already be restored:")
            print(f"             {current}")
            skipped += 1
            print()
            continue

        if original.exists():
            print(f"  [SKIP]  File already exists at original location:")
            print(f"          {original}")
            skipped += 1
            print()
            continue

        if DRY_RUN:
            print(f"  [WOULD RESTORE] {current}")
            print(f"              →  {original}")
            restored += 1
        else:
            try:
                original.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(current), str(original))
                print(f"  [RESTORED] {current}")
                print(f"          →  {original}")
                restored += 1
            except Exception as e:
                print(f"  [ERROR]  {current}")
                print(f"           Reason: {e}")
                errors += 1
        print()

    print("=" * 65)
    print("SUMMARY")
    if DRY_RUN:
        print(f"  Would restore  : {restored}")
    else:
        print(f"  Restored       : {restored}")
    print(f"  Skipped        : {skipped}")
    print(f"  Errors         : {errors}")
    print("=" * 65)


# ── Entry point ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    pos_args = [a for a in sys.argv[1:]
                if not a.startswith("--") and a not in (
                    _filter_cat or "", _filter_method or "")]

    if not pos_args:
        print("Usage: python undo_duplicates.py <path_to_csv_report> [options]")
        print()
        print("Options:")
        print("  --dry-run                      Preview only, nothing moves")
        print("  --list                         Full summary of the CSV contents")
        print("  --list-categories              Show categories and match methods")
        print("  --filter-category CATEGORY     Only undo a specific category")
        print("  --filter-method METHOD         Only undo a specific match method")
        print()
        print("Examples:")
        print(r'  python undo_duplicates.py "C:\Music\report.csv"')
        print(r'  python undo_duplicates.py "C:\Music\report.csv" --dry-run')
        print(r'  python undo_duplicates.py "C:\Music\report.csv" --list')
        print(r'  python undo_duplicates.py "C:\Music\report.csv" --list-categories')
        print(r'  python undo_duplicates.py "C:\Music\report.csv" --filter-category "Exact Match"')
        print(r'  python undo_duplicates.py "C:\Music\report.csv" --filter-method "audio fingerprint"')
        print(r'  python undo_duplicates.py "C:\Music\report.csv" --filter-method "audio fingerprint" --dry-run')
        sys.exit(1)

    csv_file = Path(pos_args[0].strip('"'))

    if LIST_SUMMARY:
        cmd_list(csv_file)
    elif LIST_CATEGORIES:
        cmd_list_categories(csv_file)
    else:
        undo(csv_file)
